import Head from "next/head";
import Navbar from "../component/Navbar";
import Body from "../component/Body";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Health.clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Body />
    </div>
  );
}
